### ISSUE TITLE
Mac OS X: Database disk image is malformed

### ISSUE THREAD

**Issue by Booklover70** [Philantrop/calibre-ios-reader-applications#130]
Hi Wulf,

I had problems with my connection between Calibre and Marvin ever since Marvin's v 2.0. I did what I learnt from various messages (I have the latest plugin version) and now my Ipad is detected by Calibre - which is rather nice - however when I try to connect them I get an error. Here is the error message. Is there anything I can do to make it work, please? Thanks!

calibre, version 2.5.0
ERROR: Error: Error communicating with device

database disk image is malformed

Traceback (most recent call last):
  File "site-packages/calibre/gui2/device.py", line 87, in run
  File "site-packages/calibre/gui2/device.py", line 502, in _books
  File "/var/folders/h6/js5p7d5x3kdczqb56f1w8dkm0000gn/T/calibre_2.5.0_tmp_ieHJ5A/MqLmap_ios_local_db/Marvin_overlays.py", line 310, in books
DatabaseError: database disk image is malformed

**Comment by MrUnderhill** [comment]
I know what I'm writing sounds like I an an idiot; I am not, I'm just not a geek but a retired prof of Literature & Performance--the product of a Bush-destroyed Interdisciplinary Humanities Advanced Grad Studies program in the Uni of TX sys.  I am having this problem since upgrading to Yosemite, but not via iPhone, just with the mail program, and I don't know if it's Calibre's internal email or my MacBook Pro, circa Fall 2011 sans "Retina".  I have a library worthy of Alexandria, and I can't share it with anyone.  I would appreciate ANY help, and so would the starving County Libraries of Ireland who depend on me to feed them.  Irish gov't put a moratorium on new books four+ years ago, and EVERY Irish school child--even those in abject poverty are required to buy their own books.  I sincerely need help with my meta-ethical & solely individual method of keeping learning alive for all who desire it in Ireland, a country that has given so much beauty, poetry, plays, novels, William Rowan Hamilton's quaternions (without those we wouldn't be cyber-communicating, would we?  This is a sincere SOS since I am dying and need to get these books in readable condition to librarians, schoolchildren, any anyone who can't afford to buy knowledge.  Please help me.

**Comment by Philantrop** [comment]
As per the previous comment, this issue was resolved. Thanks, ShellShock/Polyfun for figuring this out.
